### PR TITLE
Use @actions/core.exportVariable instead of set-env

### PR DESCRIPTION
**Pull request by stigok**
`set-env` is now deprecated. `@actions/core` exposes `exportVariable`
to be used instead.

https://github.com/actions/toolkit/tree/main/packages/core#exporting-variables

I guess the large diffs in .js is due to UNIX vs Windows line endings.

Cherry-picked from #19

### CODE REVIEW

**Comment by ds-ms** [comment]
Have you tested with your branch in your workflows?

**Comment by stigok** [comment]
This actually doesn't work using `@master` right now. I will investigate.

**Comment by ds-ms** [comment]
@master doesn't work because they don't have `node_modules` in them. You'll have to try using `stigok/k8s-set-context@releases/v1` for testing

**Comment by shigupt202** [comment]
@stigok I tested it with your release work. I still see the warning in logs. Am I missing something?
image

**Comment by ds-ms** [comment]
@shigupt202 I suppose the actions/core lib is not updated here yet

**Comment by ds-ms** [comment]
This is https://github.com/Azure/k8s-set-context/pull/15 still open

**Comment by stigok** [comment]
So this looks okay? Tested the action using `stigok/k8s-set-context@releases/v1` with success, however, as @ds-ms says, the warning still appears.
As you say, the only place `set-env` is still present is at node_modules/@actions/core/lib/core.js:38

**Comment by ds-ms** [comment]
Let's fix #15 and then you can rebase and validate. 😃 

Or if you're willing, you could update the package version in your branch and run `npm install --production` locally. And check in the newly added `node_modules` to this PR.

**Comment by stigok** [comment]
I'll wait for #15 :)

**Comment by stigok** [comment]
Is this correct? 8d92b0b

**Comment by shigupt202** [comment]
This looks good to me.

**Review by shigupt202 — APPROVED** [review]

**Comment by ds-ms** [comment]
I think it's missing a few refs. This upgrade should have had `@babel` refs in the `package-lock.json` file, did you amend it?

**Comment by stigok** [comment]
I simply set `@actions/core": "^1.2.6",`  in package.json and ran `npm install --production`. Then added a new commit.
There seems to be some line-ending changes since I'm on Linux. This might be an issue for diffs.

**Comment by shigupt202** [comment]
@ds-ms I tested the changes and it's working fine. For some reason `@babel` references are not present in the packag-lock.json, but I think we can go ahead with these changes as it's removing the warning.

**Comment by ds-ms** [comment]
@shigupt202 do you want to pick up the port of the `package.json` changes to master?

**Comment by shigupt202** [comment]
`package.json` changes are already there in master. But we need to port the other changes done in this PR to master, i.e., replacing `set-env` with `exportVariable`. I'll do it.

**Comment by shigupt202** [comment]
This change is already present in master because of https://github.com/Azure/k8s-set-context/pull/18

**Comment by stigok** [comment]
@shigupt202 no it's not. The package-lock has it at 1.1.0 in master

**Comment by shigupt202** [comment]
@stigok I think it's 1.2.6. See [this](https://github.com/Azure/k8s-set-context/blob/master/package-lock.json#L8)

**Pull request merged**
